-- Telegram v2: multiple chat ids, webhook secret, refresh marker.
--
-- telegram_chat_id (single text) becomes telegram_chat_ids (JSON array).
-- telegram_webhook_secret authorizes the bot webhook callback; it is
-- generated by the Worker on first registration (low-value credential).
-- telegram_refresh_at is the marker the /refresh command writes and the
-- SSE stream watches to make an open dashboard refetch.

ALTER TABLE settings ADD COLUMN telegram_chat_ids TEXT;

UPDATE settings
SET telegram_chat_ids = json_array(telegram_chat_id)
WHERE telegram_chat_id IS NOT NULL AND telegram_chat_id != '';

ALTER TABLE settings DROP COLUMN telegram_chat_id;

ALTER TABLE settings ADD COLUMN telegram_webhook_secret TEXT;

ALTER TABLE settings ADD COLUMN telegram_refresh_at INTEGER;